enableGlobalCache: true

logFilters:
  - level: discard
    text: "api@workspace:api provides graphql (p201cc) with version 15.8.0, which doesn't satisfy what graphql-relay requests"
  - code: YN0060
    level: error

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.0.0-rc.2.cjs
